name: USDT Watcher v2

on:
  schedule:
    - cron: "2-59/5 * * * *"
   # كل 5 دقائق
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ✅ حفظ state.json بين التشغيلات
      - name: Restore state cache
        uses: actions/cache@v4
        with:
          path: state.json
          key: usdt-state-${{ github.ref }}
          restore-keys: |
            usdt-state-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run watcher
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TRONGRID_API_KEY: ${{ secrets.TRONGRID_API_KEY }}
          WATCH_ADDRESS: ${{ secrets.WATCH_ADDRESS }}
        run: python usdt_watcher.py
